

export const occupationList: string[] = [
  "Actor or comedian",
  "Animator",
  "Announcer or other broadcaster",
  "Author or writer",
  "Conductor, composer or arranger",
  "Conservator or curator",
  "Creative designer",
  "Dancer",
  "Digital Marketing",
  "Digital content or social media",
  "Editor",
  "Fashion or costume design",
  "Film or video camera operator",
  "Graphic designer or illustrator",
  "Instructor",
  "Journalist",
  "Make-up artist",
  "Model",
  "Musician or singer",
  "Other",
  "Other culture and entertainment employee",
  "Other media employee",
  "Other performer or arts employee",
  "Painter, sculptor or other visual artist",
  "Photographer or videographer",
  "Presenter or Host",
  "Producer, director, choreographer or similar",
  "Tattoo artist or similar",
  "Technician or similar",
  "Translator or interpreter",
];
